global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: 'miruni-monitor'

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'miruni-backend'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['app:8080']
    scrape_interval: 10s

